### ISSUE TITLE
no remove option for genome comparison tracks

### ISSUE THREAD

**Issue by yilingchou** [epgg/eg#14]
For Genome comparison tracks, I think it would be nice to add a "Remove" button to the float tool box like other tracks, such that users can remove these tracks easily if they don't need to display these tracks anymore.  It also provide a more uniform user interface.

**Comment by smhsu** [comment]
I just realized that I had fixed this a couple of months ago.

commit 757e0b243386430f1fd05f72cfa098f3b86d6d3b closes #14
