### ISSUE TITLE
LD plot coloring

### ISSUE THREAD

**Issue by EvoAlias** [epgg/eg#17]
As previously discussed, Haploview has as general coloring scheme and scoring scheme for Hapmap data. There are two scores available (D' and R square) and the standard color scheme in D'/LOD (red) although R square can also be used (black and white). Our visualization is currently done in green, so it might be nice to keep to the standard coloring, but allow for user input. Data with no value is displayed in a gray/purple color in the D' plot.  It would be nice if the user could change the color scheme based on a desired threshold for R square/D' (possibly set with a default of .8). The haploview.jar is easy to download and they include sample data if you want to take a look at the coloring.  

![d prime scoring](https://cloud.githubusercontent.com/assets/8665173/10087313/d24e1eb2-62d8-11e5-9331-4671a964a8d5.png)
![r square scoring](https://cloud.githubusercontent.com/assets/8665173/10087314/d432741c-62d8-11e5-9571-eb871aadbc99.png)

**Comment by lidaof** [comment]
@debugpoint136 could you look into this? Thanks.

**Comment by debugpoint136** [comment]
Working on it now . . Thanks!

**Comment by debugpoint136** [comment]
Patch fix applied on a test instance. Check and let me know.
http://epgg-test.wustl.edu/browser/?genome=hg18&gftk=hapmap_r27_MEX,show

**Comment by debugpoint136** [comment]
Hi Renee, 
Could you please document your follow-up question/suggestion here in detail, that would be handy. 
Thanks!

**Comment by debugpoint136** [comment]
Daofeng - Find below the patch fix for the color changes I just showed you -

Patch fix applied  - 

325 base.js
![](https://dl.dropboxusercontent.com/spa/ry0atqxaxd315xf/0j7u2xfc.png)

6085 base.js

![](https://dl.dropboxusercontent.com/spa/ry0atqxaxd315xf/pwyo63c-.png)

**Comment by EvoAlias** [comment]
Hey,

Yeah I think fbin should also be removed as a scoring metric since it is
really an index metric and not a score.

On Fri, Sep 25, 2015 at 12:37 PM, Deepak Purushotham <
notifications@github.com> wrote:

> Hi Renee,
> Could you please document your follow-up question/suggestion here in
> detail, that would be handy.
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/epgg/eg/issues/17#issuecomment-143297684.

## 

_Renee Sears_

_PhD Candidate, Wang LabHuman and Statistical Genetics Program_

_Division of Biology and Biomedical Sciences_

*Washington University in St. Louis *

**Comment by lidaof** [comment]
the fin is already removed for the scoring.
