### ISSUE TITLE
Deleting Genome Comparison Track

### ISSUE THREAD

**Issue by EvoAlias** [epgg/eg#20]
I don't think it is currently possible to delete a genome comparison track. Can you add this functionality?

**Comment by debugpoint136** [comment]
Solution -
1. Go to "Tracks" and "Custom Tracks"
   ![](https://dl.dropboxusercontent.com/spa/ry0atqxaxd315xf/x1cdd1-5.png)
2. Click "List of all"

![](https://dl.dropboxusercontent.com/spa/ry0atqxaxd315xf/0o6dlkep.png)
1. You will see a panel which lists all the Genome Comparison tracks added so far. You can delete the ones , by clicking the "Delete" 

![](https://dl.dropboxusercontent.com/spa/ry0atqxaxd315xf/lco5txbi.png)
