### ISSUE TITLE
information icon doesn't display on Windows

### ISSUE THREAD

**Issue by nrockweiler** [epgg/eg#28]
I'm using chrome on Windows 8.  The information icon in the facet table doesn't display correctly:
![image](https://cloud.githubusercontent.com/assets/8428293/10402111/f5abafc6-6e88-11e5-95b4-3c95c13e66bb.png)

**Comment by smhsu** [comment]
Seems to be working on Windows 10.  Windows 8 is now obsolete anyway, so I shall close this.
