### ISSUE TITLE
What does member tracks :  mean in methylC?

### ISSUE THREAD

**Issue by debugpoint136** [epgg/eg#29]
![](https://dl.dropboxusercontent.com/spa/ry0atqxaxd315xf/meq0x7f-.png)
_Member tracks :_

**Comment by lidaof** [comment]
fixed. thanks for reporting this bug.

![image](https://user-images.githubusercontent.com/102806/28439645-5ffd6c72-6d68-11e7-9f66-c7e87e058e63.png)
