### ISSUE TITLE
Toggle button to disable the yellow overlay that highlights searched genes

### ISSUE THREAD

**Issue by debugpoint136** [epgg/eg#34]
Hi again !
I hope you are well. I showed your browser to my PI and labmates and they are very happy with it !
However, is there a way to disable the yellow overlay that highlights searched genes ? It is quite annoying with heatmap data since it becomes difficult to compare the intensity of what is inside the overlay with the outside...

![](https://dl.dropboxusercontent.com/spa/ry0atqxaxd315xf/5zhvubfi.png)
- Requested by Google+ user : [Carlo Yague](https://plus.google.com/103183897010533564980/posts/bTQWJFjrpoQ)

**Comment by lidaof** [comment]
see the code change in 209645441dbaad574ade508ec94419d8c0e98cd7 for this feature. 

![screen shot 2016-01-25 at 11 49 47 am](https://cloud.githubusercontent.com/assets/102806/12559295/e6a8db0e-c359-11e5-8c6f-30b5390c2401.png)

![screen shot 2016-01-25 at 11 49 58 am](https://cloud.githubusercontent.com/assets/102806/12559298/eb6e9836-c359-11e5-8f33-ddc2fc8975d8.png)
