### ISSUE TITLE
Scatter Plot Dot Types Not Working

### ISSUE THREAD

**Issue by EvoAlias** [epgg/eg#35]
Hey,

There are 4 types of dots available in the scatter plot app, but circle and disc create box and square dots again instead of their correct dot type.

**Comment by EvoAlias** [comment]
Also the scatter plot reset button does not seem to have any function. Maybe just take it off?

**Comment by smhsu** [comment]
Commit 030e210533669cb6256e9fde3520310ac337276e fixes #35 (dot types, see scp.js)
Commit 1afb50159074138ab58cd3f1cb94f878388160aa fixes #35 (reset button)
