### ISSUE TITLE
Custom Hi-C data

### ISSUE THREAD

**Issue by will-NYGC** [epgg/eg#47]
I have some hi-C data that i formatted into this format shown on the wiki:
chr1,713605,715737     chr1,720589,722848      2

but it crashes everytime I try to upload. I don' t think they're too big, ~15Mb, as it's only a low depth test run. Any suggestions how to see my data on your browser? thanks.

**Comment by lidaof** [comment]
Hi @will-NYGC , do you mind put few lines of your data here for us to debug? Thanks.

**Comment by will-NYGC** [comment]
I’ve tried both formats
ftp://ftp.nygenome.org/data2/Sample_Astro_2607_1000000_iced.bed
and
ftp://ftp.nygenome.org/data2/Sample_Astro_2607_1000000_iced.bg

do i need integer only scores?

On Feb 22, 2016, at 3:57 PM, Daofeng Li <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @will-NYGChttps://github.com/will-NYGC , do you mind put few lines of your data here for us to debug? Thanks.

—
Reply to this email directly or view it on GitHubhttps://github.com/epgg/eg/issues/47#issuecomment-187379259.

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by lidaof** [comment]
Hi @will-NYGC, for the first example of your file, do you use bgzip to compress and tabix to index (see http://wiki.wubrowse.org/Long-range)?
We are testing your 2nd example and will let you know.

**Comment by will-NYGC** [comment]
Yea I tried with index. It loads but I don’t see any data. I thought maybe it was my data but I couldn’t tell b/c the other file won’t load at all. any help would be appreciated.

will

On Feb 23, 2016, at 1:04 PM, Daofeng Li <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @will-NYGChttps://github.com/will-NYGC, for the first example of your file, do you use bgzip to compress and tabix to index (see http://wiki.wubrowse.org/Long-range)?
We are testing your 2nd example and will let you know.

—
Reply to this email directly or view it on GitHubhttps://github.com/epgg/eg/issues/47#issuecomment-187820338.

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by lidaof** [comment]
If you submit URL has this tabix'ed track file, it should be loaded. do you try refresh cache on this track if you didn't see any data displayed? Or use a different file name? can you send me the URL as well?

The 2nd option using file upload is not recommended since it's support limited file size, while seems we have some issues for this function now and I am finding out why.
Thank you Will.

**Comment by will-NYGC** [comment]
ok… i’ll stick with URL option.

ftp://ftp.nygenome.org/data2/Sample_Astro_2607_1000000_iced.bed.gz

I’m not sure why I load it in (with new name) and nothing shows up even if I navigate to specific locations copied from file that definitely have data:
chr1    2000000 3000000 chr1:3000000-4000000,235.962856 207     +

thank you, Daofeng, for your help.

On Feb 23, 2016, at 2:12 PM, Daofeng Li <notifications@github.com<mailto:notifications@github.com>> wrote:

If you submit URL has this tabix'ed track file, it should be loaded. do you try refresh cache on this track if you didn't see any data displayed? Or use a different file name? can you send me the URL as well?

The 2nd option using file upload is not recommended since it's support limited file size, while seems we have some issues for this function now and I am finding out why.
Thank you Will.

—
Reply to this email directly or view it on GitHubhttps://github.com/epgg/eg/issues/47#issuecomment-187846547.

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.

**Comment by lidaof** [comment]
Hi Will,

sorry for late response, was just back from a meeting.
I tried your URL and it works pretty well though, do you tried zoom out a little bit for the data to be displayed? 

![image](https://cloud.githubusercontent.com/assets/102806/13265569/400b4d6c-da39-11e5-8630-af927e7b6f72.png)

**Comment by will-NYGC** [comment]
oh wow. ok great. i must be doing something wrong but glad to see file is fine. i’ll keep trying. thanks so much for your help.

will

On Feb 23, 2016, at 3:26 PM, Daofeng Li <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Will,

sorry for late response, was just back from a meeting.
I tried your URL and it works pretty well though, do you tried zoom out a little bit for the data to be displayed?

[image]https://cloud.githubusercontent.com/assets/102806/13265569/400b4d6c-da39-11e5-8630-af927e7b6f72.png

—
Reply to this email directly or view it on GitHubhttps://github.com/epgg/eg/issues/47#issuecomment-187888258.

This electronic message is intended for the use of the named recipient only, and may contain information that is confidential, privileged or protected from disclosure under applicable law. If you are not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any reading, disclosure, dissemination, distribution, copying or use of the contents of this message including any of its attachments is strictly prohibited. If you have received this message in error or are not the named recipient, please notify us immediately by contacting the sender at the electronic mail address noted above, and destroy all copies of this message. Please note, the recipient should check this email and any attachments for the presence of viruses. The organization accepts no liability for any damage caused by any virus transmitted by this email.
