### ISSUE TITLE
Problem uploading custom track

### ISSUE THREAD

**Issue by yichao-cai** [epgg/eg#53]
Hi,

I've been trying to upload my custom bigWig track to Epigenome Browser.

I followed the wiki to use cyverse to host my bigWig file.
These are the URL of my file:
1:https://de.cyverse.org/anon-files/iplant/home/yichao_cai/GM12878_H3K27ac.bigWig
2:https://de.cyverse.org/anon-files/iplant/home/yichao_cai/GM12878_H3K27me3.bigWig
3:https://de.cyverse.org/anon-files/iplant/home/yichao_cai/K562_H3K27ac.bigWig
4:https://de.cyverse.org/anon-files/iplant/home/yichao_cai/K562_H3K27me3.bigWig

I can successfully add the link 1 and link 3. However, I always have issue loading link 2 and link 4.
The error is : 
```
Failed to add this track.
If this is an updated version of a previously used track, you need to refresh cache.
```

Fist I thought it is a naming issue, then I tried a different track name but still cannot upload.
I tried the example upload and it worked exactly fine.
I tried delete the uploaded track and re-upload it again. Also fine.
I tried refresh cache but still got the same error.

Can you help me figure out what might go wrong?
Thank you so much!

P.S. The cyverse seems to support bigWig format now, you may want to update your wiki.

Best regards,
Yichao

**Comment by lidaof** [comment]
Hi @YichaoCaiDBS, thanks for reporting this.
It's pretty weird though certain of your bigWig files don't work...do you generate the bigWig all the same way?
Anyway...I actually just tried your 2nd and 4th link, both of which work fine...could you please retry?

ps, yeah, we have been contacting CyVerse people for the bigWig support and adding our browser link. Thanks. we will update the wiki page.

**Comment by yichao-cai** [comment]
Hi @lidaof ,

I retry to upload the files and now it works just fine. 
For the bigWig file, I have them downloaded from UCSC, so they should not be a problem. 
The reason why I have this issue may be the file hosting service. The network might seem to be the only explanation.
I also wonder if the browser support coloring according to different categories, rather than taking a continuous score as color scale? Let's say I have already cluster my feature into different categories and I want to have them displayed in different colors?

Thank you so much for the prompt reply!

Yichao

**Comment by lidaof** [comment]
Sure! Do you mean like a chromHMM track? that way you have to use tabix bedgraph format (http://wiki.wubrowse.org/Hammock#category), which Cyverse doesn't support. we could host the data for you if there is not too much data.

**Comment by lidaof** [comment]
hi @YichaoCaiDBS, a follow up with you that do you want us to host the data for you? Please let us know. thanks.
