### ISSUE TITLE
Using multiple base genome for comparative genomics

### ISSUE THREAD

**Issue by mayanknkchoudhary** [epgg/eg#56]
Attaching an example  session:
<img width="1631" alt="screen shot 2017-04-20 at 1 38 57 pm" src="https://cloud.githubusercontent.com/assets/6150499/25247314/1c00b996-25d0-11e7-9cb4-b521ffc3d4a6.png">

Description: It is a hg19 genome brolywser with some human data tracks. There is a hg19-to-mm9 genome comparison annotation track below which I had some mouse data. Now ideally, I'd expect that the mouse data that has been loaded is displaying the data for the corresponding region in the mouse genome. However, these mouse tracks are being confined to the basal human genome track (which I'm afraid doesn't make complete biological sense, as the underlying sequences are different)

A good fix would be to have a basal mouse genome and have the "basal-mouse-and-human" genomes converse (via the genome comparison/liftOver tools). That way the mouse data is being aligned and displayed on the mouse genome that is corresponding to the human genome regions, accordingly. 

Hope this helps! Feel free to ask any questions you may have—happy to discuss.

Session can also be accessed at: goo.gl/lF0hjG

P.S. The tracks also seem to not be holding onto their order in which they were displayed when the session was saved in the first place.

**Comment by debugpoint136** [comment]
Great description of the issue. Thanks @mayanknkchoudhary ! Will keep you posted with updates on this.

**Comment by lidaof** [comment]
session function fixed in c4cb942
