### ISSUE TITLE
Wiki error: Genomealign track definition in datahub 

### ISSUE THREAD

**Issue by mayanknkchoudhary** [epgg/eg#57]
In the wiki:
{
type:'genomelink',
querygenome…
…
},

type attribute should read **genomealign** and not genomelink

Wiki page link: http://wiki.wubrowse.org/Genome_alignment#Genomealign_track_definition_in_datahub

**Comment by lidaof** [comment]
Thanks so much for reporting this @mayanknkchoudhary .
Fixed.
