### ISSUE TITLE
Moving across coordinates with multiple long-range interaction tracks causes the browser to crash

### ISSUE THREAD

**Issue by mayanknkchoudhary** [epgg/eg#58]
Upon trying to navigate to chr1:74305798-74305818 after loading all relevant long range interaction tracks from [here](http://wangftp.wustl.edu/~mchoudhary/human_HiCCUPS/):

Error: Crashed upon ajaxX
Session: http://epigenomegateway.wustl.edu/browser/?genome=hg19&session=p2GkpebZ2j&statusId=1421379953

![screen shot 2017-06-05 at 4 58 20 pm](https://cloud.githubusercontent.com/assets/6150499/26805201/7c512948-4a10-11e7-911b-007ff529d85d.png)

**Comment by lidaof** [comment]
the error seems happened quite random...sometime the data was not done transferring before the rendering. While your session seems works fine with me :)
