### ISSUE TITLE
Issues with Yeast Genome

### ISSUE THREAD

**Issue by arnavm** [epgg/eg#60]
There are a few issues with the yeast (sacCer3) genome:
 
1. Yeast chromosomes are numbered using Roman numerals. When sorted alphabetically, chrIX (9) falls between 4 (chrIV) and 5 (chrV). The default ordering should be numerical.

2. The yeast genes are labeled by their systematic names, e.g. YGR254W. However, most people using the browser (and yeast biologists) will want to search by standard names, e.g ENO1, which are more meaningful and easier to remember. An example of the mapping between standard and systematic names can be found here: http://www.yeastgenome.org/locus/S000003486/overview

3. When installing the browser locally, I cannot search by gene in sacCer3. I believe this is because sacCer3 has not been added to the "load" repository. Please update accordingly.

Thanks!

**Comment by lidaof** [comment]
Working on the fix, will update asap.

**Comment by lidaof** [comment]
thanks again for reporting this @arnavm .

Fixed 7716c82.
