### ISSUE TITLE
Error embedding a browser to a website with SSL (https://)

### ISSUE THREAD

**Issue by leepc12** [epgg/eg#65]
I am trying to embed your browser to a website with SSL, but got `Mixed Content` error.

![image](https://user-images.githubusercontent.com/8625660/32191170-5be78d48-bd6d-11e7-855b-66e095ea7cb3.png)

I have tried all workarounds like `<iframe>` and copying all `.js` files to a local directory but all failed. Web browsers always complain about SSL.

Is there any plan to support SSL on your browser?

**Comment by lidaof** [comment]
Hi @leepc12 , thanks for raising this point. We are working on the HTTPS support actually, will update you asap.

**Comment by leepc12** [comment]
@lidaof Hello folks, sorry bothering you again.

Do you guys have sort of ETA for this SSL feature? We are looking forward to embed it to our site :)

**Comment by lidaof** [comment]
Hi @leepc12, yes, I just get the https setup done on yesterday, wanted to do more tests before I get back to you. You can access the scripts using https URL now. Let me know if you find any issue please. Thanks.

**Comment by leepc12** [comment]
Thanks so much for the update @lidaof .
It seems to work but still gets `Mixed contents` errors and the browser tracks do not fit into the embedded window.

![image](https://user-images.githubusercontent.com/8625660/36013439-173f38ac-0d19-11e8-9b85-82bb2adb9eb6.png)

**Comment by lidaof** [comment]
Hi @leepc12, sorry for late response. yes, the sukn.js error is a known bug but won't effect the browser function. for the mixed content warning the images and logos could also be accessed using https URL (while seems the URL is coded already in out hosted javascript). I will debug this and update you. Thanks.

**Comment by leepc12** [comment]
@lidaof sorry for bothering you, but is there any update on this issue?

**Comment by lidaof** [comment]
Sure. I don't think the track not fitting problem caused by `mixed content`? can you try our latest code base please? Also all our js, css, and images can be accessed by both HTTP and HTTPS..

**Comment by leepc12** [comment]
It works now. Thanks!

closing this.
