### ISSUE TITLE
javascript error when adding a new genome using epgg/eg docker image

### ISSUE THREAD

**Issue by jos4uke** [epgg/eg#76]
Hi

I tried to add a new genome using epgg/eg docker image for test purposes.
I used the wiki doc here: http://wiki.wubrowse.org/Add_a_private_genome
I followed the instructions to add Gmax_189 genome but I ended up with an error.
Then, I tried to add tair10 but again I got the same error.

Here are the commands I executed inside the docker image to add tair10:

 ```bash
# in the container
mkdir -p /srv/epgg/data/data/subtleKnife/tair10/session

# prepare genome sequence and annotation files: http://wiki.wubrowse.org/Pull_annotation_data
cd /srv/epgg/data/data/subtleKnife/tair10
wget http://epgg-test.wustl.edu/installdata/tair10/gc5Base.bigWig
wget http://epgg-test.wustl.edu/installdata/tair10/repeat.gz
wget http://epgg-test.wustl.edu/installdata/tair10/repeat.gz.tbi
wget http://epgg-test.wustl.edu/installdata/tair10/tair10Gene.gz
wget http://epgg-test.wustl.edu/installdata/tair10/tair10Gene.gz.tbi

# add sequences 
cd /srv/epgg/data/data/subtleKnife/seq
wget -b -q  wget http://epgg-test.wustl.edu/installdata/tair10.gz \
    http://epgg-test.wustl.edu/installdata/tair10.gz.tbi

# init database
mysql -u root -p
mysql > create database tair10;

# populate tair10 database
cd /root/load/tair10/
cat load.sql | mysql -u root -p tair10 --local-infile=1
cd /root/eg/config/tair10/
cat makeDb.sql | mysql -u root -p tair10 --local-infile=1

# add tracks config
cd /root/eg/config/tair10/
mkdir /srv/epgg/data/data/subtleKnife/tair10/config
rsync tracks.json /srv/epgg/data/data/subtleKnife/tair10/config/

```

Here is a screenshot: 
![washu_epigenome_browser_tair10_bug](https://user-images.githubusercontent.com/1325049/37727971-59e1c298-2d39-11e8-9c03-df1c257a0595.png)

Could you help me fix this?

Regards, 

Joseph

**Comment by lidaof** [comment]
hi @jos4uke, did you use the makeDb.sql file directly from our repo? or do you see any error message from apache's error_log file? Thanks.

**Comment by jos4uke** [comment]
Hi @lidaof, I used the makeDb.sql from your repo (the one inside the container in /root/eg/config/tair10/).

And here is the log error from apache when I tried to load tair10:

```log
# /var/log/apache2/error.log
subtileKnife starting... >>>>>
cgi param parsed
done
subtileKnife starting... >>>>>
cgi param parsed
Hooked to tair10
fetching genome info...
done
subtileKnife starting... >>>>>
cgi param parsed
Hooked to tair10
Table 'tair10.scaffoldRuntime' doesn't exist
Table 'tair10.scaffoldRuntime' doesn't exist
# /var/log/apache2/error.log

```

And here is the log error from apache when I tried to load Gmax_189:

```log
# /var/log/apache2/error.log
subtileKnife starting... >>>>>
cgi param parsed
done
subtileKnife starting... >>>>>
cgi param parsed
Hooked to Gmax_189
fetching genome info...
done
subtileKnife starting... >>>>>
cgi param parsed
Hooked to Gmax_189
Table 'Gmax_189.scaffoldRuntime' doesn't exist
Table 'Gmax_189.scaffoldRuntime' doesn't exist

```

All errors seem related to a missing *.scaffoldRuntime table.

**Comment by jos4uke** [comment]
Hi @lidaof ,

I found the missing step in database setup.
I had to apply sessionUtils.sql and it fixes the previous javascript error.

```bash
# inside the container
cat /root/eg/config/sessionUtils.sql | mysql -uroot -proot tair10

```

Then, I succeeded to access tair10 in the browser.

![washu_epigenome_browser_tair10_fixed](https://user-images.githubusercontent.com/1325049/37764548-3e41ea8e-2dc2-11e8-8f9f-65eecf1c9ab4.png)

**Comment by lidaof** [comment]
Great, @jos4uke , yeah, the error_log explained the reason. Glad you figured it out.
