### ISSUE TITLE
questions about annotationTracks.json

### ISSUE THREAD

**Issue by songtaogui** [epgg/eg#91]
Hi,

I was trying to add a genome (not publicly released) accroding to the [`Add a new genome`](https://epigenomegateway.readthedocs.io/en/latest/add.html#) tutorial. The 2bit genome file and the cytoband file are no hard to generate, but I was confused at `annotationTracks.json` file:

The example mm10 annotationTracks.json file has a `Genes` track looks like this: 
```
 "Genes": [
        {
            "name": "refGene",
            "label": "RefSeq genes",
            "filetype": "geneAnnotation"
        },
        {
            "name": "gencodeM19",
            "label": "GENCODE M19 genes",
            "options": {
                "categoryColors": {
                    "coding": "rgb(0,60,179)",
                    "nonCoding": "rgb(0,128,0)",
                    "pseudogene": "rgb(230,0,172)",
                    "problem": "rgb(255,0,0)",
                    "polyA": "rgb(0,0,51)"
                }
            },
            "filetype": "geneAnnotation"
        },
        {
            "name": "gencodeM19Basic",
            "label": "GENCODE M19 genes (basic set)",
            "options": {
                "categoryColors": {
                    "coding": "rgb(0,60,179)",
                    "nonCoding": "rgb(0,128,0)",
                    "pseudogene": "rgb(230,0,172)",
                    "problem": "rgb(255,0,0)",
                    "polyA": "rgb(0,0,51)"
                }
            },
            "filetype": "geneAnnotation"
        }
    ],
```
Unlike the `RepeatMasker` track, there are no URLs in the Gene tracks. So I was wondering that how does the browser know where to get the gene annotation infomation? Does these information store in the UCSC mm10 2bit file ?  And how can I add Gene trakcs for my genome with local annotation gff (or gtf) files? Is it the only way to use locally generated refbed files?
 
Any suggestions would be grateful.

Best wishes,

Songtao Gui

**Comment by lidaof** [comment]
Hi @songtaogui , sorry for late reply. This repo is for old browser and I assume your question is for new browser?

the gene track information are stored in mongodb database in the backend services. you can check the backend folder for more information. which genome are you working on? if it's in our list, you don't need to run the backend services.

**Comment by songtaogui** [comment]
Hi lidao,
Yes, my question is for new browser, sorry for the carelessness. 
I will move my issue to https://github.com/lidaof/eg-react/issues .
