### ISSUE TITLE
Issue in loading interaction file 

### ISSUE THREAD

**Issue by kmualim** [epgg/eg#93]
Hi, I'm uploading an interaction file to the legacy WashU browser and it's having trouble showing up.

The file is located at : http://mitra.stanford.edu/kundaje/projects/ABC_links/final_list_sorted.txt.gz

The file showed up before when I first wanted to visualize the links in 2019-5-20 but now it doesn't load onto the browser. 

Thanks!

**Comment by lidaof** [comment]
Hi @kmualim seems like a cached index problem. I just cleaned manually.
 could you please try one more time? Thanks.

**Comment by kmualim** [comment]
Hello, yup the issue has been fixed. Thanks!
